[package]
name = "forge"
version = "0.1.0"
description = "A Git aware project management system"
authors = ["Prince Lad <ladprince1112@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
serde = "1.0.228"
uuid = "1.19.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
